export const section: string;
export const sectionBreak: string;
export const introduction: string;
export const block: string;
export const pictures: string;
export const picture: string;
export const image: string;
export const description: string;
export const pdfButton: string;
