export const app: string;
export const paper: string;
export const noPrint: string;
export const noPrintInfo: string;
export const container: string;
export const profilePicture: string;
export const navigation: string;
export const navButton: string;
export const content: string;
